### ISSUE TITLE
Doesn’t work without JavaScript

### ISSUE THREAD

**Issue by aarongustafson** [davedawson/scrtchpd-lite#1]
Can you create a server side fallback?

**Comment by davedawson** [comment]
Hey @aarongustafson, thanks for the feedback! 

You're right, the saving of the note doesn't work without JS, but the writing experience remains the same. 

I'm not totally sure how to remedy this problem using a server side solution without adding a user model and allowing users to save notes to their account. Clearly this would add a lot to the project, and definitely bump it over the 10k limit. 

Am I missing a more obvious and simpler solution that you have in mind?

**Comment by aarongustafson** [comment]
I’m thinking you could save it server side as part of a session or in a
flat file. It could be implemented relatively easily in php.

If you store it on the server, you could set up a task that cleans out old
ones after a certain amount of time (since it’s a demo) buy checking for
timestamps more than a day old or something whenever a page is loaded (or,
alternately, saved).

**Comment by davedawson** [comment]
Thanks, @aarongustafson. That gives me a great place to start. I haven't done much work with PHP. But I'll take a look and see if I can figure something out!

**Comment by davedawson** [comment]
Great idea, @aarongustafson! Thanks for the push in the right direction. I didn't know you could store information like that in PHP. So cool! 

I've updated the app to run from the `index.php` file. The fallback now includes a "Save" button when JS is disabled, which allows users to save their notes as a session variable. When JS _is_ enabled, the Save button is removed, and the standard localStorage saving resumes.

**Comment by aarongustafson** [comment]
Perfect, I will re-sync!
